# Generated by Django 3.2.4 on 2023-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('evening_snacks', models.TextField()),
                ('dinner', models.TextField()),
                ('bed_snacks', models.TextField()),
            ],
        ),
    ]
